### PR TITLE
Added WBK format [Spider-Man 2, Ultimate Spider-Man]

### PR DESCRIPTION
**Pull request by NicknineTheEagle**

### CODE REVIEW

**Comment by modusc896d352** [comment]
uhhhh
**Call of Duty 2: Big Red One** also uses this wbk format, but it's stored in bigfiles instead. may i post them here?

**Comment by NicknineTheEagle** [comment]
Oh, I suspected that that game might use them. Do it.

**Comment by modusc896d352** [comment]
OK!
it won't take long.

**Comment by NicknineTheEagle** [comment]
Seems to be working fine.

**Pull request merged**
