### PR TITLE
FSB5 patch.

### PR DESCRIPTION
**Pull request by modusc896d352**
it adds two extensions from existing FSB5 meta code.
PR is currently in "draft" mode because i have yet to test it.

### CODE REVIEW

**Comment by modusc896d352** [comment]
tested the FSB5 .wav files with test.exe and they decode fine.
but foobar2000 component of vgmstream doesn't seem to work particularly well with it, so these files need their extension renamed to lwav.

**Comment by bnnm** [comment]
Please configure your IDE/git so they use \n (LF) and that doesn't change the whole fsb5.c file to \r\n (CRLF)

**Comment by modusc896d352** [comment]
i'm afraid this is going to take a while.

**Comment by modusc896d352** [comment]
uhhh something bad just happened, will have to close this PR for now.

**Pull request closed without merging**
