### PR TITLE
Cmake: Fix Celt not downloading

### PR DESCRIPTION
**Pull request by KatieFrogs**
Falls back to downloading through Git if it downloads an empty file (#1069)

### CODE REVIEW

**Comment by kode54** [comment]
You could also make the links to xiph http instead of https. Their https server is misconfigured.

**Comment by KatieFrogs** [comment]
@kode54 Absolutely not, I am not putting users at risk by using insecure protocols

**Comment by xxyzz** [comment]
Would you consider adding macOS build and test job to GitHub Actions?

**Comment by KatieFrogs** [comment]
@xxyzz Not a bad idea, unfortunately out of the scope of this particular pull request

Side note, I did attempt to make a macOS GitHub action for vgmstream before, but could not get it to compile

**Comment by bnnm** [comment]
> Absolutely not, I am not putting users at risk by using insecure protocols
Non-git downloads that aren't checked vs some kind of valid hash put users at risk anyway (https or not). Though realistically...

**Pull request merged**
